<?php

return [
	'classes' => [
		'description' => 'Create a class',
		'commands' => [
			'make:channel' => 'Channel',
			'make:console' => 'Command',
			'create:constant' => 'Constant',
			'make:controller' => 'Controller',
			'create:entity' => 'Entity',
			'make:event' => 'Event',
			'make:exception' => 'Exception',
			'create:facade' => 'Facade',
			'make:factory' => 'Factory',
			'make:job' => 'Job',
			'make:listener' => 'Listener',
			'make:mail' => 'Mail',
			'make:middleware' => 'Middleware',
			'make:migration' => 'Migration',
			'make:model' => 'Model',
			'make:notification' => 'Notification',
			'make:observer' => 'Observer',
			'make:phpclass' => 'PHP Class',
			'make:policy' => 'Policy',
			'make:provider' => 'Provider',
			'make:request' => 'Request',
			'make:resource' => 'Resource',
			'make:routefile' => 'Route',
			'make:rule' => 'Rule',
			'make:seeder' => 'Seeder',
			'make:test' => 'Testing',
		]
	],
	'resources' => [
		'description' => 'Create a file',
		'commands' => [
			'create:bitbucket-pipeline' => 'Bitbucket CI',
			'create:changelog' => 'CHANGELOG.md',
			'create:composer' => 'Composer',
			'create:config' => 'Config',
			'create:editor' => 'EditorConfig',
			'create:gitignore' => 'Git ignore',
			'create:js' => 'Javascript',
			'create:keep' => 'Keep file',
			'create:lang' => 'Lang',
			'create:webpack' => 'LaravelMix',
			'create:package-js' => 'Package.json',
			'create:phpcs' => 'PhpCS',
			'create:phpunit' => 'PHPUnit',
			'create:readme' => 'README.md',
			'create:sonar' => 'SonarConfig',
			'create:css' => 'Style',
		]
	],
];